### ISSUE TITLE
file path error in file "infostealer_browser.py"

### ISSUE THREAD

**Issue by dv0** [brad-accuvant/community-modified#27]
re.compile(".*\\\\Temporary\\\\ Internet\\ Files\\\\Content\.IE5\\\\index\.dat$", re.I)

should be:
re.compile(".*\\\\Temporary\\ Internet\\ Files\\\\Content\.IE5\\\\index\.dat$", re.I)

**Comment by brad-accuvant** [comment]
Thanks, fixed!
