### ISSUE TITLE
FP in ek_flash.py

### ISSUE THREAD

**Issue by KillerInstinct** [brad-accuvant/community-modified#79]
From Google Analytics Urchin Module (UTM)
```
//-- Google Analytics Urchin Module
//-- Copyright 2007 Google, All Rights Reserved.
```

Code snippit:

```
{
    try {
        fl = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
        f = "WIN 6,0,21,0";
        fl.AllowScriptAccess = "always";
        f = fl.GetVariable("$version");
    } catch (e) {}
}
if (f == "-") {
    try {
        fl = new ActiveXObject("ShockwaveFlash.ShockwaveFlash");
        f = fl.GetVariable("$version");
    } catch (e) {}
}
```

**Comment by kevross33** [comment]
To be honest I am unsure of the best way to negate this FP as technically this is exactly what we are looking for unless we explicitly whitelist "Google Analytics Urchin Module" if this next appears? Have you seen any other cases of FPs that are prolific?

**Comment by kevross33** [comment]
Correction: text appears (not next)

**Comment by KillerInstinct** [comment]
Yeah, I see this in many different sites, generally anything with flash, for example game advertisements, crappy website animations, among other things. Will gather some URL's later today as they come up.

**Comment by kevross33** [comment]
Hi,

Rather than a whitelist would improving on the regex improve things do you think? i.e:

.*allowscriptaccess[ \t\n]*=[ \t\n]*['\"]?always.*\<param name[ \t\n]*=.*value[ \t\n]*=.*

Alternatively though while whitelists could be used if it is fairly common perhaps reducing the cofidence and severity may also be in order and utilise other indicators of malicious/suspicious activity so at least it can be searched to try and locate interesting websites without outright saying it is malicious (although obviously this is what I would prefer although I haven't tried out cuckoosploit yet for this)?

**Comment by kevross33** [comment]
ok wildcards seemed to get removed there from the characters so you know:
wildcard = WC
.WCallowscriptaccess[ \t\n]=[ \t\n]['\"]?always.WC<param name[ \t\n]=.WCvalue[ \t\n]=.WC

**Comment by wmetcalf** [comment]
I've seen many other legit sites where this happens. This sig should probably be removed or set to a very, very low score.

**Comment by kevross33** [comment]
Hi,

I saw Brad changed its score from 3 to 2 although I guess the confidence
could also be reduced still which is currently at 50. Does this have a
better impact for you? It is unfortunate as I thought perhaps this
signature would be more useful in EK hunting and be more reliable.

Sorry for the issues this signature has caused.

**Comment by KillerInstinct** [comment]
Ideas to reduce FPs:

* Also parse for width/height >=1
* Add the hooks for call["api"].startswith("HttpAddRequestHeaders") and parse for the addition of a flash header (consistent with plugin detection)
 * You'd have to keep track of API sequencing, then you could check for the sequence of HttpAddRequestHeaders (add flash version) -> COleScript_ParseScriptText (with allowsscriptaccess=always)
